import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body suppressHydrationWarning>
                    {/* header will show on all pages */}
                    <Header />
                    <div className="flex min-h-screen">
                        {/* Sidebar */}
                        <Sidebar />
                        <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
                            {children}
                        </div>
                    </div>
                    <ToastContainer />
                </body>
            </html>
        </ClerkProvider>
    );
}
